#!/usr/bin/env python3
"""
Weekly Ingestion Job - Runs Saturday 23:00 UTC via Render Cron
Processes raw/ → wiki/ with LLM-Wiki v2 integration (MiniMax-M3)

Raw notes (pure markdown body) are ingested into wiki pages with full
LLM-Wiki frontmatter generated by ingestion_v2.py.
"""
import json
import logging
import os
import sys
import time
from datetime import datetime
from pathlib import Path

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Add bot to path
sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from bot.ingestion_v2 import ingest_raw_to_wiki
    from bot.notification import (
        notify_ingestion_start,
        notify_ingestion_success,
        notify_ingestion_failure
    )
except ImportError as e:
    logger.error(f"Failed to import ingestion module: {e}")
    sys.exit(1)


def get_vault_path() -> Path:
    """Get vault path from environment or use default."""
    vault_path_str = os.getenv("VAULT_PATH")
    if not vault_path_str:
        logger.error("VAULT_PATH environment variable not set")
        sys.exit(1)

    vault_path = Path(vault_path_str)
    if not vault_path.exists():
        logger.error(f"Vault path does not exist: {vault_path}")
        sys.exit(1)

    return vault_path


def save_ingestion_result(vault_path: Path, result: dict) -> Path:
    """Save ingestion result JSON to outputs/ingestion-reports/."""
    reports_dir = vault_path / "outputs" / "ingestion-reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d-%H%M%S")
    result_path = reports_dir / f"ingestion-{timestamp}.json"

    result_path.write_text(json.dumps(result, indent=2, ensure_ascii=False))

    logger.info(f"✅ Ingestion result saved: {result_path}")
    return result_path


def main():
    """Run weekly ingestion job."""
    logger.info("=" * 80)
    logger.info("WEEKLY INGESTION JOB STARTED (Render Cron - Saturday 23:00 UTC)")
    logger.info("Using: bot.ingestion_v2 (MiniMax-M3)")
    logger.info("=" * 80)

    vault_path = get_vault_path()
    logger.info(f"Vault path: {vault_path}")

    # Count files before processing
    raw_path = vault_path / "raw"
    file_count = len(list(raw_path.glob("**/*.md"))) if raw_path.exists() else 0
    logger.info(f"Files to process: {file_count}")
    notify_ingestion_start(str(vault_path), file_count)

    start_time = time.time()

    try:
        result = ingest_raw_to_wiki(vault_path)

        duration = time.time() - start_time

        # Log summary
        logger.info("=" * 80)
        logger.info("INGESTION RESULT")
        logger.info("=" * 80)
        logger.info(f"  Status:          {result.get('status')}")
        logger.info(f"  Processed:       {result.get('processed', 0)}")
        logger.info(f"  Failed:          {result.get('failed', 0)}")
        logger.info(f"  Trashed:         {result.get('trashed', 0)}")
        logger.info(f"  Total raw files: {result.get('total', 0)}")
        logger.info(f"  LLM Provider:    {result.get('llm_provider', 'unknown')}")
        logger.info(f"  LLM Model:       {result.get('llm_model', 'unknown')}")
        logger.info(f"  LLM Skipped:     {result.get('skip_llm', False)}")
        logger.info(f"  Broken wikilinks:{result.get('broken_wikilinks', 0)}")
        logger.info(f"  Duration:        {duration:.1f}s")
        logger.info("=" * 80)

        # Save result JSON
        report_path = save_ingestion_result(vault_path, result)

        if result.get("status") in ("success", "partial"):
            logger.info("✅ INGESTION JOB COMPLETED")
            notify_ingestion_success(
                str(vault_path),
                result.get('processed', 0),
                result.get('failed', 0),
                duration
            )
            return 0
        else:
            logger.error("❌ INGESTION JOB FAILED")
            error_msg = result.get('message', 'Unknown error')
            logger.error(f"Error: {error_msg}")
            notify_ingestion_failure(str(vault_path), error_msg)
            return 1

    except Exception as e:
        duration = time.time() - start_time
        logger.error("=" * 80)
        logger.error("❌ INGESTION JOB CRASHED")
        logger.error("=" * 80)
        logger.exception(f"Unexpected error: {e}")
        notify_ingestion_failure(str(vault_path), str(e))
        return 1


if __name__ == "__main__":
    sys.exit(main())
